[package]
authors = ["Tom HoulÃ© <tom@tomhoule.com>"]
name = "graphqlient"
version = "0.1.0"

[dependencies]
failure = "*"
graphql-parser = "*"
structopt = "*"

[dependencies.quote]
features = []
version = "*"
